@echo off
echo Starting Crime Reporting System...
echo -----------------------------------
echo Clearing old background connections (Port 5001)...
FOR /F "tokens=5" %%a IN ('netstat -aon ^| find "5001" ^| find "LISTENING"') DO taskkill /f /pid %%a 2>nul

echo Installing any missing dependencies...
call npm install --silent
echo Starting Backend and Frontend Servers...
call npm run dev
pause
